apiVersion: apps/v1
kind: StatefulSet
metadata:
     name: elasticsearch
     namespace: kube-system
     labels:
        app: jaeger
        jaeger-infra: elasticsearch-statefulset
spec: 
    serviceName: elasticsearch
    selector: 
      matchLabels:
        app: jaeger-elasticsearch
    replicas: 1
    template:
       metadata:
            labels:
               app: jaeger-elasticsearch
               jaeger-infra: elasticsearch-replica
       spec:
            containers:
               - name: elasticsearch
                 image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
                 imagePullPolicy: Always
                 command:
                   - bin/elasticsearch
                 args:
                   - "-Ehttp.host=0.0.0.0"
                   - "-Etransport.host=127.0.0.1"
                 volumeMounts:
                   - name: data
                     mountPath: /data
                 readinessProbe:
                   exec:
                     command:
                     - curl
                     - --fail
                     - --silent
                     - --output
                     - /dev/null
                     - --user
                     - elastic:changeme
                     - localhost:9200
                   initialDelaySeconds: 5
                   periodSeconds: 5
                   timeoutSeconds: 4
            volumes:
                - name: data
                  emptyDir: {}
