apiVersion: v1
kind: Service
metadata:
     name: elasticsearch
     namespace: kube-system
     labels:
        app: jaeger
        jaeger-infra: elasticsearch-service
spec:
    selector:
      app: jaeger-elasticsearch
    ports:
    - name: http
      port: 9200
      protocol: TCP
      nodePort: 30093
    - port: 9300
      name: transport
    type: NodePort
