apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-tracing-agent
  namespace: kube-system
  labels:
    app: istio-tracing-agent
    chart: tracing-agent-0.1.0
    release: istio
    heritage: Tiller
spec:
  selector:
    matchLabels:
      app: istio-tracing-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-tracing-agent
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:latest
          ports:
            - containerPort: 5778
              protocol: TCP
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
          command:
            - "/go/bin/agent-linux"
            - "--collector.host-port=jaeger-collector.kube-system.svc.cluster.local:14267"
